name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - run: |
          yarn install --frozen-lockfile
          yarn build
          export WWW_COMMIT=`git rev-parse HEAD`
      - name: Publish PR change to www branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: www
          publish_dir: ./build
          destination_dir: ./
          force_orphan: true
          cname: onprem.in
